-- ******************************** SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: AdWorkSnowflakeProject, v27 by retinder.labana@sqldbm.com *


-- ************************************** table_27
CREATE TABLE table_27
(

);

-- ************************************** table_26
CREATE TABLE table_26
(

)
COMMENT = 'fgfdgf';

-- ************************************** table_25
CREATE TABLE table_25
(
 customer_space_id  NOT NULL,

 CONSTRAINT pk_1 PRIMARY KEY ( customer_space_id )
)
COMMENT = 'fgdfgfd';

-- ************************************** adworks.dim_scenario
CREATE TABLE adworks.dim_scenario
(
 scenario_key  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Scenario Identifier',
 scenario_name varchar(50) COMMENT 'Name of the Scenario',
 created_by    varchar(50) NOT NULL COMMENT 'Who Created this Scenario',
 created_date  timestamp_ntz(9) NOT NULL COMMENT 'Scenario Creation Date',
 updated_date  timestamp_ntz(9) NOT NULL,
 updated_by    varchar(50) NOT NULL,
 test_col      varchar(50) NOT NULL,

 CONSTRAINT pk_dim_scenario PRIMARY KEY ( scenario_key )
)
COMMENT = 'Dimension Scenario';

-- ************************************** adworks.dim_sales_territory
CREATE TABLE adworks.dim_sales_territory
(
 sales_territory_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 sales_territory_alternate_key number(38,0),
 sales_territory_region        varchar(50) NOT NULL,
 sales_territory_country       varchar(50) NOT NULL,
 sales_territory_group         varchar(50),

 CONSTRAINT pk_dim_sales_territory PRIMARY KEY ( sales_territory_key )
)
COMMENT = 'Sales Territory data';

-- ************************************** adworks.dim_promotion
CREATE TABLE adworks.dim_promotion
(
 promotion_key              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 promotion_alternate_key    number(38,0),
 english_promotion_name     varchar(255),
 spanish_promotion_name     varchar(255),
 french_promotion_name      varchar(255),
 discount_pct               float,
 english_promotion_type     varchar(50),
 spanish_promotion_type     varchar(50),
 french_promotion_type      varchar(50),
 english_promotion_category varchar(50),
 spanish_promotion_category varchar(50),
 french_promotion_category  varchar(50),
 min_qty                    number(38,0),
 max_qty                    number(38,0),

 CONSTRAINT pk_dim_promotion PRIMARY KEY ( promotion_key )
);

-- ************************************** adworks.dim_product_category
CREATE TABLE adworks.dim_product_category
(
 product_category_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 product_category_alternate_key number(38,0),
 english_product_category_name  varchar(50) NOT NULL,
 spanish_product_category_name  varchar(50) NOT NULL,
 french_product_category_name   varchar(50) NOT NULL,

 CONSTRAINT pk_dim_product_category PRIMARY KEY ( product_category_key )
);

-- ************************************** adworks.dim_organization
CREATE TABLE adworks.dim_organization
(
 organization_key        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 parent_organization_key number(38,0),
 percentage_of_ownership varchar(16),
 organization_name       varchar(50),
 currency_key            number(38,0),

 CONSTRAINT pk_dim_organization PRIMARY KEY ( organization_key )
)
COMMENT = 'Dimension for Organizational Data';

-- ************************************** adworks.dim_geography
CREATE TABLE adworks.dim_geography
(
 geography_key               number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 city                        varchar(30),
 state_province_code         varchar(3),
 state_province_name         varchar(50),
 country_region_code         varchar(3),
 english_country_region_name varchar(50),
 spanish_country_region_name varchar(50),
 french_country_region_name  varchar(50),
 postal_code                 varchar(15),
 sales_territory_key         number(38,0),
 ip_address_locator          varchar(15),

 CONSTRAINT pk_dim_geography PRIMARY KEY ( geography_key )
);

-- ************************************** adworks.dim_date
CREATE TABLE adworks.dim_date
(
 date_key                 number(38,0) NOT NULL,
 full_date_alternate_key  date NOT NULL,
 day_number_of_week       number(38,0) NOT NULL,
 english_day_name_of_week varchar(10) NOT NULL,
 spanish_day_name_of_week varchar(10) NOT NULL,
 french_day_name_of_week  varchar(10) NOT NULL,
 day_number_of_month      number(38,0) NOT NULL,
 day_number_of_year       number(38,0) NOT NULL,
 week_number_of_year      number(38,0) NOT NULL,
 english_month_name       varchar(10) NOT NULL,
 spanish_month_name       varchar(10) NOT NULL,
 french_month_name        varchar(10) NOT NULL,
 month_number_of_year     number(38,0) NOT NULL,
 calendar_quarter         number(38,0) NOT NULL,
 calendar_year            number(38,0) NOT NULL,
 calendar_semester        number(38,0) NOT NULL,
 fiscal_quarter           number(38,0) NOT NULL,
 fiscal_year              number(38,0) NOT NULL,
 fiscal_semester          number(38,0) NOT NULL,

 CONSTRAINT pk_dim_date PRIMARY KEY ( date_key )
)
COMMENT = 'Dimension for Date time';

-- ************************************** adworks.dim_currency
CREATE TABLE adworks.dim_currency
(
 currency_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Currency Identifier',
 currency_alternate_key varchar(3) NOT NULL COMMENT 'Alternate Currency Identifier',
 currency_name          varchar(50) NOT NULL COMMENT 'Name of the Currency',

 CONSTRAINT pk_dim_currency PRIMARY KEY ( currency_key )
)
COMMENT = 'Dimension for Currency Data';

-- ************************************** adworks.new_fact_currency_rate
CREATE TABLE adworks.new_fact_currency_rate
(
 average_rate    float,
 currency_id     varchar(3),
 currency_date   date,
 end_of_day_rate float,
 currency_key    number(38,0),
 date_key        number(38,0),
 tester          date NOT NULL,

 CONSTRAINT fk_new_fact_currency_rate_469 FOREIGN KEY ( currency_key ) REFERENCES adworks.dim_currency ( currency_key ),
 CONSTRAINT fk_new_fact_currency_rate_471 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key )
);

-- ************************************** adworks.fact_survey_response
CREATE TABLE adworks.fact_survey_response
(
 survey_response_key              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 date_key                         number(38,0) NOT NULL,
 customer_key                     number(38,0) NOT NULL,
 product_category_key             number(38,0) NOT NULL,
 english_product_category_name    varchar(50) NOT NULL,
 product_subcategory_key          number(38,0) NOT NULL,
 english_product_subcategory_name varchar(50) NOT NULL,

 CONSTRAINT fk_fact_survey_response_465 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_survey_response_467 FOREIGN KEY ( product_category_key ) REFERENCES adworks.dim_product_category ( product_category_key )
);

-- ************************************** adworks.fact_sales_quota
CREATE TABLE adworks.fact_sales_quota
(
 sales_quota_key    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 employee_key       number(38,0) NOT NULL,
 date_key           number(38,0) NOT NULL,
 calendar_year      number(38,0) NOT NULL,
 calendar_quarter   number(38,0) NOT NULL,
 sales_amount_quota number(38,0) NOT NULL,

 CONSTRAINT fk_fact_sales_quota_463 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key )
);

-- ************************************** adworks.fact_product_inventory
CREATE TABLE adworks.fact_product_inventory
(
 product_key   number(38,0) NOT NULL,
 date_key      number(38,0) NOT NULL,
 movement_date date NOT NULL,
 unit_cost     number(38,0) NOT NULL,
 units_in      number(38,0) NOT NULL,
 units_out     number(38,0) NOT NULL,
 units_balance number(38,0) NOT NULL,

 CONSTRAINT fk_fact_product_inventory_443 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key )
);

-- ************************************** adworks.fact_currency_rate
CREATE TABLE adworks.fact_currency_rate
(
 currency_key    number(38,0) NOT NULL,
 date_key        number(38,0) NOT NULL,
 average_rate    float NOT NULL,
 end_of_day_rate float NOT NULL,

 CONSTRAINT fk_fact_currency_rate_413 FOREIGN KEY ( currency_key ) REFERENCES adworks.dim_currency ( currency_key ),
 CONSTRAINT fk_fact_currency_rate_415 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key )
);

-- ************************************** adworks.dim_reseller
CREATE TABLE adworks.dim_reseller
(
 reseller_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 geography_key          number(38,0),
 reseller_alternate_key varchar(15),
 phone                  varchar(25),
 business_type          varchar(20) NOT NULL,
 reseller_name          varchar(50) NOT NULL,
 number_employees       number(38,0),
 order_frequency        varchar(1),
 order_month            number(38,0),
 first_order_year       number(38,0),
 last_order_year        number(38,0),
 product_line           varchar(50),
 address_line_1         varchar(60),
 address_line_2         varchar(60),
 annual_sales           number(38,0),
 bank_name              varchar(50),
 min_payment_type       number(38,0),
 min_payment_amount     number(38,0),
 annual_revenue         number(38,0),
 year_opened            number(38,0),

 CONSTRAINT pk_dim_reseller PRIMARY KEY ( reseller_key ),
 CONSTRAINT fk_dim_reseller_411 FOREIGN KEY ( geography_key ) REFERENCES adworks.dim_geography ( geography_key )
);

-- ************************************** adworks.dim_product_subcategory
CREATE TABLE adworks.dim_product_subcategory
(
 product_subcategory_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 product_subcategory_alternate_key number(38,0),
 english_product_subcategory_name  varchar(50) NOT NULL,
 spanish_product_subcategory_name  varchar(50) NOT NULL,
 french_product_subcategory_name   varchar(50) NOT NULL,
 product_category_key              number(38,0),
 tester_2                          date NOT NULL,

 CONSTRAINT pk_dim_product_subcategory PRIMARY KEY ( product_subcategory_key ),
 CONSTRAINT fk_dim_product_subcategory_409 FOREIGN KEY ( product_category_key ) REFERENCES adworks.dim_product_category ( product_category_key )
);

-- ************************************** adworks.dim_employee
CREATE TABLE adworks.dim_employee
(
 employee_key                              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 parent_employee_key                       number(38,0),
 employee_national_id_alternate_key        varchar(15),
 parent_employee_national_id_alternate_key varchar(15),
 sales_territory_key                       number(38,0),
 first_name                                varchar(50) NOT NULL,
 last_name                                 varchar(50) NOT NULL,
 middle_name                               varchar(50),
 name_style                                number(38,0) NOT NULL,
 title                                     varchar(50),
 hire_date                                 date,
 birth_date                                date,
 login_id                                  varchar(256),
 email_address                             varchar(50),
 phone                                     varchar(25),
 marital_status                            varchar(1),
 emergency_contact_name                    varchar(50),
 emergency_contact_phone                   varchar(25),
 salaried_flag                             number(38,0),
 gender                                    varchar(1),
 pay_frequency                             number(38,0),
 base_rate                                 number(38,0),
 vacation_hours                            number(38,0),
 sick_leave_hours                          number(38,0),
 current_flag                              number(38,0) NOT NULL,
 sales_person_flag                         number(38,0) NOT NULL,
 department_name                           varchar(50),
 start_date                                date,
 end_date                                  date,
 status                                    varchar(50),

 CONSTRAINT pk_dim_employee PRIMARY KEY ( employee_key ),
 CONSTRAINT fk_dim_employee_403 FOREIGN KEY ( parent_employee_key ) REFERENCES adworks.dim_employee ( employee_key ),
 CONSTRAINT fk_dim_employee_405 FOREIGN KEY ( sales_territory_key ) REFERENCES adworks.dim_sales_territory ( sales_territory_key )
)
COMMENT = 'This table holds all Employee Information';

-- ************************************** adworks.dim_customer
CREATE TABLE adworks.dim_customer
(
 customer_key            number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Customer Identifier',
 geography_key           number(38,0) COMMENT 'Geographic informatio',
 customer_alternate_key  varchar(15) NOT NULL COMMENT 'Alternate Key',
 title                   varchar(8) COMMENT 'Title of the Customer',
 first_name              varchar(50),
 middle_name             varchar(50),
 last_name               varchar(50),
 name_style              varchar(5),
 birth_date              date,
 marital_status          varchar(1),
 suffix                  varchar(10),
 gender                  varchar(1),
 email_address           varchar(50),
 yearly_income           number(38,0),
 total_children          number(38,0),
 number_children_at_home number(38,0),
 english_education       varchar(40),
 spanish_education       varchar(40),
 french_education        varchar(40),
 english_occupation      varchar(100),
 spanish_occupation      varchar(100),
 french_occupation       varchar(100),
 house_owner_flag        varchar(1),
 number_cars_owned       number(38,0),
 address_line            varchar(120),
 address_line_2          varchar(120),
 phone                   varchar(20),
 date_first_purchase     date,
 commute_distance        varchar(15),

 CONSTRAINT pk_dim_customer PRIMARY KEY ( customer_key ),
 CONSTRAINT fk_dim_customer_401 FOREIGN KEY ( geography_key ) REFERENCES adworks.dim_geography ( geography_key )
)
COMMENT = 'Dimension for Customer Data';

-- ************************************** table_24
CREATE TABLE table_24
(
 date_key number(38,0) NOT NULL,

 CONSTRAINT pk_1 PRIMARY KEY ( date_key ),
 CONSTRAINT fk_40 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key )
);

-- ************************************** adworks.dim_product
CREATE TABLE adworks.dim_product
(
 product_key              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 product_alternate_key    varchar(25),
 product_subcategory_key  number(38,0),
 weight_unit_measure_code varchar(3),
 size_unit_measure_code   varchar(3),
 english_product_name     varchar(50) NOT NULL,
 spanish_product_name     varchar(50),
 french_product_name      varchar(50),
 standard_cost            number(38,0),
 finished_goods_flag      number(38,0) NOT NULL,
 color                    varchar(15) NOT NULL,
 safety_stock_level       number(38,0),
 reorder_point            number(38,0),
 list_price               number(38,0),
 size                     varchar(50),
 size_range               varchar(50),
 weight                   float,
 days_to_manufacture      number(38,0),
 product_line             varchar(2),
 dealer_price             number(38,0),
 class                    varchar(2),
 style                    varchar(2),
 model_name               varchar(50),
 english_description      varchar(400),
 french_description       varchar(400),
 chinese_description      varchar(400),
 arabic_description       varchar(400),
 hebrew_description       varchar(400),
 thai_description         varchar(400),
 german_description       varchar(400),
 japanese_description     varchar(400),
 turkish_description      varchar(400),
 status                   varchar(7),
 tester_2                  NOT NULL,
 tester_2_1                NOT NULL,

 CONSTRAINT pk_dim_product PRIMARY KEY ( product_key ),
 CONSTRAINT fk_dim_product_407 FOREIGN KEY ( product_subcategory_key ) REFERENCES adworks.dim_product_subcategory ( product_subcategory_key )
);

-- ************************************** adworks.dim_department_group
CREATE TABLE adworks.dim_department_group
(
 department_group_key        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 parent_department_group_key number(38,0),
 department_group_name       varchar(50),

 CONSTRAINT pk_dim_department_group PRIMARY KEY ( department_group_key )
)
COMMENT = 'Dimension for Department groups';

-- ************************************** table_23
CREATE TABLE table_23
(
 department_group_key number(38,0) NOT NULL,

 CONSTRAINT pk_1 PRIMARY KEY ( department_group_key ),
 CONSTRAINT fk_38 FOREIGN KEY ( department_group_key ) REFERENCES adworks.dim_department_group ( department_group_key )
)
COMMENT = 'hdgfh';

-- ************************************** adworks.fact_reseller_sales
CREATE TABLE adworks.fact_reseller_sales
(
 product_key             number(38,0) NOT NULL,
 order_date_key          number(38,0) NOT NULL,
 due_date_key            number(38,0) NOT NULL,
 ship_date_key           number(38,0) NOT NULL,
 reseller_key            number(38,0) NOT NULL,
 employee_key            number(38,0) NOT NULL,
 promotion_key           number(38,0) NOT NULL,
 currency_key            number(38,0) NOT NULL,
 sales_territory_key     number(38,0) NOT NULL,
 sales_order_number      varchar(20) NOT NULL,
 sales_order_line_number number(38,0) NOT NULL,
 revision_number         number(38,0),
 order_quantity          number(38,0),
 unit_price              number(38,0),
 extended_amount         number(38,0),
 unit_price_discount_pct float,
 discount_amount         float,
 product_standard_cost   number(38,0),
 total_product_cost      number(38,0),
 sales_amount            number(38,0),
 tax_amt                 number(38,0),
 freight                 number(38,0),
 carrier_tracking_number varchar(25),
 customer_po_number      varchar(25),
 col_25                   NOT NULL,

 CONSTRAINT fk_fact_reseller_sales_445 FOREIGN KEY ( product_key ) REFERENCES adworks.dim_product ( product_key ),
 CONSTRAINT fk_fact_reseller_sales_447 FOREIGN KEY ( reseller_key ) REFERENCES adworks.dim_reseller ( reseller_key ),
 CONSTRAINT fk_fact_reseller_sales_449 FOREIGN KEY ( employee_key ) REFERENCES adworks.dim_employee ( employee_key ),
 CONSTRAINT fk_fact_reseller_sales_451 FOREIGN KEY ( promotion_key ) REFERENCES adworks.dim_promotion ( promotion_key ),
 CONSTRAINT fk_fact_reseller_sales_453 FOREIGN KEY ( currency_key ) REFERENCES adworks.dim_currency ( currency_key ),
 CONSTRAINT fk_fact_reseller_sales_455 FOREIGN KEY ( sales_territory_key ) REFERENCES adworks.dim_sales_territory ( sales_territory_key ),
 CONSTRAINT fk_fact_reseller_sales_457 FOREIGN KEY ( order_date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_reseller_sales_459 FOREIGN KEY ( due_date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_reseller_sales_461 FOREIGN KEY ( ship_date_key ) REFERENCES adworks.dim_date ( date_key )
)
COMMENT = 'Fact data of Reseller Sales';

-- ************************************** adworks.fact_internet_sales
CREATE TABLE adworks.fact_internet_sales
(
 product_key             number(38,0) NOT NULL,
 order_date_key          number(38,0) NOT NULL,
 due_date_key            number(38,0) NOT NULL,
 ship_date_key           number(38,0) NOT NULL,
 customer_key            number(38,0) NOT NULL,
 promotion_key           number(38,0) NOT NULL,
 currency_key            number(38,0) NOT NULL,
 sales_territory_key     number(38,0) NOT NULL,
 sales_order_number      varchar(20) NOT NULL,
 sales_order_line_number number(38,0) NOT NULL,
 revision_number         number(38,0) NOT NULL,
 order_quantity          number(38,0) NOT NULL,
 unit_price              number(38,0) NOT NULL,
 extended_amount         number(38,0) NOT NULL,
 unit_price_discount_pct float NOT NULL,
 discount_amount         float NOT NULL,
 product_standard_cost   number(38,0) NOT NULL,
 total_product_cost      number(38,0) NOT NULL,
 sales_amount            number(38,0) NOT NULL,
 tax_amt                 number(38,0) NOT NULL,
 freight                 number(38,0) NOT NULL,
 carrier_tracking_number varchar(25),
 customer_po_number      varchar(25),

 CONSTRAINT fk_fact_internet_sales_427 FOREIGN KEY ( product_key ) REFERENCES adworks.dim_product ( product_key ),
 CONSTRAINT fk_fact_internet_sales_429 FOREIGN KEY ( customer_key ) REFERENCES adworks.dim_customer ( customer_key ),
 CONSTRAINT fk_fact_internet_sales_431 FOREIGN KEY ( promotion_key ) REFERENCES adworks.dim_promotion ( promotion_key ),
 CONSTRAINT fk_fact_internet_sales_433 FOREIGN KEY ( currency_key ) REFERENCES adworks.dim_currency ( currency_key ),
 CONSTRAINT fk_fact_internet_sales_435 FOREIGN KEY ( sales_territory_key ) REFERENCES adworks.dim_sales_territory ( sales_territory_key ),
 CONSTRAINT fk_fact_internet_sales_437 FOREIGN KEY ( order_date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_internet_sales_439 FOREIGN KEY ( due_date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_internet_sales_441 FOREIGN KEY ( ship_date_key ) REFERENCES adworks.dim_date ( date_key )
)
COMMENT = 'Fact table to hold Currency Data';

-- ************************************** adworks.fact_finance
CREATE TABLE adworks.fact_finance
(
 finance_key          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 date_key             number(38,0) NOT NULL,
 organization_key     number(38,0) NOT NULL,
 department_group_key number(38,0) NOT NULL,
 scenario_key         number(38,0) NOT NULL,
 account_key          number(38,0) NOT NULL,
 amount               float NOT NULL,

 CONSTRAINT fk_fact_finance_417 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_finance_419 FOREIGN KEY ( organization_key ) REFERENCES adworks.dim_organization ( organization_key ),
 CONSTRAINT fk_fact_finance_421 FOREIGN KEY ( department_group_key ) REFERENCES adworks.dim_department_group ( department_group_key ),
 CONSTRAINT fk_fact_finance_423 FOREIGN KEY ( scenario_key ) REFERENCES adworks.dim_scenario ( scenario_key )
)
COMMENT = 'Facts for Finance';

-- ************************************** table_28
CREATE TABLE table_28
(
 employee_key number(38,0) NOT NULL,

 CONSTRAINT pk_1 PRIMARY KEY ( employee_key ),
 CONSTRAINT fk_42 FOREIGN KEY ( employee_key ) REFERENCES adworks.dim_employee ( employee_key )
);

-- ************************************** ADWORKS.DIM_PRODUCT_CAT_SUBCAT_V
CREATE VIEW SQLDBM_DEMO.ADWORKS.DIM_PRODUCT_CAT_SUBCAT_V(
	"ProductKey",
	"ProductAlternateKey",
	"ProductSubcategoryKey",
	"WeightUnitMeasureCode",
	"SizeUnitMeasureCode",
	"EnglishProductName",
	"StandardCost",
	"FinishedGoodsFlag",
	"Color",
	"SafetyStockLevel",
	"ReorderPoint",
	"ListPrice",
	"Size",
	"SizeRange",
	"Weight",
	"DaysToManufacture",
	"ProductLine",
	"DealerPrice",
	"Class",
	"Style",
	"ModelName",
	"EnglishDescription",
	"Status",
	"ProductCategoryKey",
	"ProductCategoryAlternateKey",
	"EnglishProductCategoryName",
	"EnglishProductSubcategoryName"
) COMMENT='Product details with cat and subcat english names. For fwd/rev engineering'
 as
(
WITH cat_subcat as (
SELECT cat.* , sub."ProductSubcategoryKey" as "SubProductSubcategoryKey", sub."EnglishProductSubcategoryName"  FROM "DimProductCategory" cat
inner join  "DimProductSubcategory" sub
on  cat."ProductCategoryKey" = sub."ProductCategoryKey"
) 
  select 
 "ProductKey"           
, "ProductAlternateKey"  
, "ProductSubcategoryKey"
, "WeightUnitMeasureCode"
, "SizeUnitMeasureCode"  
, "EnglishProductName"   
, "StandardCost"         
, "FinishedGoodsFlag"    
, "Color"                
, "SafetyStockLevel"     
, "ReorderPoint"         
, "ListPrice"            
, "Size"                 
 ,"SizeRange"            
 ,"Weight"               
 ,"DaysToManufacture"    
 ,"ProductLine"          
 ,"DealerPrice"          
 ,"Class"                
 ,"Style"                
 ,"ModelName"            
 ,"EnglishDescription"   
 ,"Status"                   
,"ProductCategoryKey"         
,"ProductCategoryAlternateKey"
,"EnglishProductCategoryName" 
,"EnglishProductSubcategoryName"
 from "DimProduct" prod
  left join cat_subcat 
  on prod."ProductSubcategoryKey" = cat_subcat."SubProductSubcategoryKey"
);

