-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.fact_product_inventory
CREATE TABLE adworks.fact_product_inventory
(
 product_key   number(38,0) NOT NULL,
 date_key      number(38,0) NOT NULL,
 movement_date date NOT NULL,
 unit_cost     number(38,0) NOT NULL,
 units_in      number(38,0) NOT NULL,
 units_out     number(38,0) NOT NULL,
 units_balance number(38,0) NOT NULL,

 CONSTRAINT fk_fact_product_inventory_443 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key )
);
