-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.new_fact_currency_rate
CREATE TABLE adworks.new_fact_currency_rate
(
 average_rate    float,
 currency_id     varchar(3),
 currency_date   date,
 end_of_day_rate float,
 currency_key    number(38,0),
 date_key        number(38,0),
 tester          date NOT NULL,

 CONSTRAINT fk_new_fact_currency_rate_469 FOREIGN KEY ( currency_key ) REFERENCES adworks.dim_currency ( currency_key ),
 CONSTRAINT fk_new_fact_currency_rate_471 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key )
);
