-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_currency
CREATE TABLE adworks.dim_currency
(
 currency_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Currency Identifier',
 currency_alternate_key varchar(3) NOT NULL COMMENT 'Alternate Currency Identifier',
 currency_name          varchar(50) NOT NULL COMMENT 'Name of the Currency',

 CONSTRAINT pk_dim_currency PRIMARY KEY ( currency_key )
)
COMMENT = 'Dimension for Currency Data';
