-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_product
CREATE TABLE adworks.dim_product
(
 product_key              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 product_alternate_key    varchar(25),
 product_subcategory_key  number(38,0),
 weight_unit_measure_code varchar(3),
 size_unit_measure_code   varchar(3),
 english_product_name     varchar(50) NOT NULL,
 spanish_product_name     varchar(50),
 french_product_name      varchar(50),
 standard_cost            number(38,0),
 finished_goods_flag      number(38,0) NOT NULL,
 color                    varchar(15) NOT NULL,
 safety_stock_level       number(38,0),
 reorder_point            number(38,0),
 list_price               number(38,0),
 size                     varchar(50),
 size_range               varchar(50),
 weight                   float,
 days_to_manufacture      number(38,0),
 product_line             varchar(2),
 dealer_price             number(38,0),
 class                    varchar(2),
 style                    varchar(2),
 model_name               varchar(50),
 english_description      varchar(400),
 french_description       varchar(400),
 chinese_description      varchar(400),
 arabic_description       varchar(400),
 hebrew_description       varchar(400),
 thai_description         varchar(400),
 german_description       varchar(400),
 japanese_description     varchar(400),
 turkish_description      varchar(400),
 status                   varchar(7),
 tester_2                  NOT NULL,
 tester_2_1                NOT NULL,

 CONSTRAINT pk_dim_product PRIMARY KEY ( product_key ),
 CONSTRAINT fk_dim_product_407 FOREIGN KEY ( product_subcategory_key ) REFERENCES adworks.dim_product_subcategory ( product_subcategory_key )
);
