-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_department_group
CREATE TABLE adworks.dim_department_group
(
 department_group_key        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 parent_department_group_key number(38,0),
 department_group_name       varchar(50),

 CONSTRAINT pk_dim_department_group PRIMARY KEY ( department_group_key )
)
COMMENT = 'Dimension for Department groups';
