-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.fact_internet_sales
CREATE TABLE adworks.fact_internet_sales
(
 product_key             number(38,0) NOT NULL,
 order_date_key          number(38,0) NOT NULL,
 due_date_key            number(38,0) NOT NULL,
 ship_date_key           number(38,0) NOT NULL,
 customer_key            number(38,0) NOT NULL,
 promotion_key           number(38,0) NOT NULL,
 currency_key            number(38,0) NOT NULL,
 sales_territory_key     number(38,0) NOT NULL,
 sales_order_number      varchar(20) NOT NULL,
 sales_order_line_number number(38,0) NOT NULL,
 revision_number         number(38,0) NOT NULL,
 order_quantity          number(38,0) NOT NULL,
 unit_price              number(38,0) NOT NULL,
 extended_amount         number(38,0) NOT NULL,
 unit_price_discount_pct float NOT NULL,
 discount_amount         float NOT NULL,
 product_standard_cost   number(38,0) NOT NULL,
 total_product_cost      number(38,0) NOT NULL,
 sales_amount            number(38,0) NOT NULL,
 tax_amt                 number(38,0) NOT NULL,
 freight                 number(38,0) NOT NULL,
 carrier_tracking_number varchar(25),
 customer_po_number      varchar(25),

 CONSTRAINT fk_fact_internet_sales_427 FOREIGN KEY ( product_key ) REFERENCES adworks.dim_product ( product_key ),
 CONSTRAINT fk_fact_internet_sales_429 FOREIGN KEY ( customer_key ) REFERENCES adworks.dim_customer ( customer_key ),
 CONSTRAINT fk_fact_internet_sales_431 FOREIGN KEY ( promotion_key ) REFERENCES adworks.dim_promotion ( promotion_key ),
 CONSTRAINT fk_fact_internet_sales_433 FOREIGN KEY ( currency_key ) REFERENCES adworks.dim_currency ( currency_key ),
 CONSTRAINT fk_fact_internet_sales_435 FOREIGN KEY ( sales_territory_key ) REFERENCES adworks.dim_sales_territory ( sales_territory_key ),
 CONSTRAINT fk_fact_internet_sales_437 FOREIGN KEY ( order_date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_internet_sales_439 FOREIGN KEY ( due_date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_internet_sales_441 FOREIGN KEY ( ship_date_key ) REFERENCES adworks.dim_date ( date_key )
)
COMMENT = 'Fact table to hold Currency Data';
