-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_sales_territory
CREATE TABLE adworks.dim_sales_territory
(
 sales_territory_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 sales_territory_alternate_key number(38,0),
 sales_territory_region        varchar(50) NOT NULL,
 sales_territory_country       varchar(50) NOT NULL,
 sales_territory_group         varchar(50),

 CONSTRAINT pk_dim_sales_territory PRIMARY KEY ( sales_territory_key )
)
COMMENT = 'Sales Territory data';
