-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_date
CREATE TABLE adworks.dim_date
(
 date_key                 number(38,0) NOT NULL,
 full_date_alternate_key  date NOT NULL,
 day_number_of_week       number(38,0) NOT NULL,
 english_day_name_of_week varchar(10) NOT NULL,
 spanish_day_name_of_week varchar(10) NOT NULL,
 french_day_name_of_week  varchar(10) NOT NULL,
 day_number_of_month      number(38,0) NOT NULL,
 day_number_of_year       number(38,0) NOT NULL,
 week_number_of_year      number(38,0) NOT NULL,
 english_month_name       varchar(10) NOT NULL,
 spanish_month_name       varchar(10) NOT NULL,
 french_month_name        varchar(10) NOT NULL,
 month_number_of_year     number(38,0) NOT NULL,
 calendar_quarter         number(38,0) NOT NULL,
 calendar_year            number(38,0) NOT NULL,
 calendar_semester        number(38,0) NOT NULL,
 fiscal_quarter           number(38,0) NOT NULL,
 fiscal_year              number(38,0) NOT NULL,
 fiscal_semester          number(38,0) NOT NULL,

 CONSTRAINT pk_dim_date PRIMARY KEY ( date_key )
)
COMMENT = 'Dimension for Date time';
