-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.fact_sales_quota
CREATE TABLE adworks.fact_sales_quota
(
 sales_quota_key    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 employee_key       number(38,0) NOT NULL,
 date_key           number(38,0) NOT NULL,
 calendar_year      number(38,0) NOT NULL,
 calendar_quarter   number(38,0) NOT NULL,
 sales_amount_quota number(38,0) NOT NULL,

 CONSTRAINT fk_fact_sales_quota_463 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key )
);
