-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_scenario
CREATE TABLE adworks.dim_scenario
(
 scenario_key  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Scenario Identifier',
 scenario_name varchar(50) COMMENT 'Name of the Scenario',
 created_by    varchar(50) NOT NULL COMMENT 'Who Created this Scenario',
 created_date  timestamp_ntz(9) NOT NULL COMMENT 'Scenario Creation Date',
 updated_date  timestamp_ntz(9) NOT NULL,
 updated_by    varchar(50) NOT NULL,
 test_col      varchar(50) NOT NULL,

 CONSTRAINT pk_dim_scenario PRIMARY KEY ( scenario_key )
)
COMMENT = 'Dimension Scenario';
