-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.fact_reseller_sales
CREATE TABLE adworks.fact_reseller_sales
(
 product_key             number(38,0) NOT NULL,
 order_date_key          number(38,0) NOT NULL,
 due_date_key            number(38,0) NOT NULL,
 ship_date_key           number(38,0) NOT NULL,
 reseller_key            number(38,0) NOT NULL,
 employee_key            number(38,0) NOT NULL,
 promotion_key           number(38,0) NOT NULL,
 currency_key            number(38,0) NOT NULL,
 sales_territory_key     number(38,0) NOT NULL,
 sales_order_number      varchar(20) NOT NULL,
 sales_order_line_number number(38,0) NOT NULL,
 revision_number         number(38,0),
 order_quantity          number(38,0),
 unit_price              number(38,0),
 extended_amount         number(38,0),
 unit_price_discount_pct float,
 discount_amount         float,
 product_standard_cost   number(38,0),
 total_product_cost      number(38,0),
 sales_amount            number(38,0),
 tax_amt                 number(38,0),
 freight                 number(38,0),
 carrier_tracking_number varchar(25),
 customer_po_number      varchar(25),
 col_25                   NOT NULL,

 CONSTRAINT fk_fact_reseller_sales_445 FOREIGN KEY ( product_key ) REFERENCES adworks.dim_product ( product_key ),
 CONSTRAINT fk_fact_reseller_sales_447 FOREIGN KEY ( reseller_key ) REFERENCES adworks.dim_reseller ( reseller_key ),
 CONSTRAINT fk_fact_reseller_sales_449 FOREIGN KEY ( employee_key ) REFERENCES adworks.dim_employee ( employee_key ),
 CONSTRAINT fk_fact_reseller_sales_451 FOREIGN KEY ( promotion_key ) REFERENCES adworks.dim_promotion ( promotion_key ),
 CONSTRAINT fk_fact_reseller_sales_453 FOREIGN KEY ( currency_key ) REFERENCES adworks.dim_currency ( currency_key ),
 CONSTRAINT fk_fact_reseller_sales_455 FOREIGN KEY ( sales_territory_key ) REFERENCES adworks.dim_sales_territory ( sales_territory_key ),
 CONSTRAINT fk_fact_reseller_sales_457 FOREIGN KEY ( order_date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_reseller_sales_459 FOREIGN KEY ( due_date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_reseller_sales_461 FOREIGN KEY ( ship_date_key ) REFERENCES adworks.dim_date ( date_key )
)
COMMENT = 'Fact data of Reseller Sales';
