-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_promotion
CREATE TABLE adworks.dim_promotion
(
 promotion_key              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 promotion_alternate_key    number(38,0),
 english_promotion_name     varchar(255),
 spanish_promotion_name     varchar(255),
 french_promotion_name      varchar(255),
 discount_pct               float,
 english_promotion_type     varchar(50),
 spanish_promotion_type     varchar(50),
 french_promotion_type      varchar(50),
 english_promotion_category varchar(50),
 spanish_promotion_category varchar(50),
 french_promotion_category  varchar(50),
 min_qty                    number(38,0),
 max_qty                    number(38,0),

 CONSTRAINT pk_dim_promotion PRIMARY KEY ( promotion_key )
);
