-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.fact_survey_response
CREATE TABLE adworks.fact_survey_response
(
 survey_response_key              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 date_key                         number(38,0) NOT NULL,
 customer_key                     number(38,0) NOT NULL,
 product_category_key             number(38,0) NOT NULL,
 english_product_category_name    varchar(50) NOT NULL,
 product_subcategory_key          number(38,0) NOT NULL,
 english_product_subcategory_name varchar(50) NOT NULL,

 CONSTRAINT fk_fact_survey_response_465 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_survey_response_467 FOREIGN KEY ( product_category_key ) REFERENCES adworks.dim_product_category ( product_category_key )
);
