-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_customer
CREATE TABLE adworks.dim_customer
(
 customer_key            number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Customer Identifier',
 geography_key           number(38,0) COMMENT 'Geographic informatio',
 customer_alternate_key  varchar(15) NOT NULL COMMENT 'Alternate Key',
 title                   varchar(8) COMMENT 'Title of the Customer',
 first_name              varchar(50),
 middle_name             varchar(50),
 last_name               varchar(50),
 name_style              varchar(5),
 birth_date              date,
 marital_status          varchar(1),
 suffix                  varchar(10),
 gender                  varchar(1),
 email_address           varchar(50),
 yearly_income           number(38,0),
 total_children          number(38,0),
 number_children_at_home number(38,0),
 english_education       varchar(40),
 spanish_education       varchar(40),
 french_education        varchar(40),
 english_occupation      varchar(100),
 spanish_occupation      varchar(100),
 french_occupation       varchar(100),
 house_owner_flag        varchar(1),
 number_cars_owned       number(38,0),
 address_line            varchar(120),
 address_line_2          varchar(120),
 phone                   varchar(20),
 date_first_purchase     date,
 commute_distance        varchar(15),

 CONSTRAINT pk_dim_customer PRIMARY KEY ( customer_key ),
 CONSTRAINT fk_dim_customer_401 FOREIGN KEY ( geography_key ) REFERENCES adworks.dim_geography ( geography_key )
)
COMMENT = 'Dimension for Customer Data';
