-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_reseller
CREATE TABLE adworks.dim_reseller
(
 reseller_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 geography_key          number(38,0),
 reseller_alternate_key varchar(15),
 phone                  varchar(25),
 business_type          varchar(20) NOT NULL,
 reseller_name          varchar(50) NOT NULL,
 number_employees       number(38,0),
 order_frequency        varchar(1),
 order_month            number(38,0),
 first_order_year       number(38,0),
 last_order_year        number(38,0),
 product_line           varchar(50),
 address_line_1         varchar(60),
 address_line_2         varchar(60),
 annual_sales           number(38,0),
 bank_name              varchar(50),
 min_payment_type       number(38,0),
 min_payment_amount     number(38,0),
 annual_revenue         number(38,0),
 year_opened            number(38,0),

 CONSTRAINT pk_dim_reseller PRIMARY KEY ( reseller_key ),
 CONSTRAINT fk_dim_reseller_411 FOREIGN KEY ( geography_key ) REFERENCES adworks.dim_geography ( geography_key )
);
