-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_product_category
CREATE TABLE adworks.dim_product_category
(
 product_category_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 product_category_alternate_key number(38,0),
 english_product_category_name  varchar(50) NOT NULL,
 spanish_product_category_name  varchar(50) NOT NULL,
 french_product_category_name   varchar(50) NOT NULL,

 CONSTRAINT pk_dim_product_category PRIMARY KEY ( product_category_key )
);
