-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_employee
CREATE TABLE adworks.dim_employee
(
 employee_key                              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 parent_employee_key                       number(38,0),
 employee_national_id_alternate_key        varchar(15),
 parent_employee_national_id_alternate_key varchar(15),
 sales_territory_key                       number(38,0),
 first_name                                varchar(50) NOT NULL,
 last_name                                 varchar(50) NOT NULL,
 middle_name                               varchar(50),
 name_style                                number(38,0) NOT NULL,
 title                                     varchar(50),
 hire_date                                 date,
 birth_date                                date,
 login_id                                  varchar(256),
 email_address                             varchar(50),
 phone                                     varchar(25),
 marital_status                            varchar(1),
 emergency_contact_name                    varchar(50),
 emergency_contact_phone                   varchar(25),
 salaried_flag                             number(38,0),
 gender                                    varchar(1),
 pay_frequency                             number(38,0),
 base_rate                                 number(38,0),
 vacation_hours                            number(38,0),
 sick_leave_hours                          number(38,0),
 current_flag                              number(38,0) NOT NULL,
 sales_person_flag                         number(38,0) NOT NULL,
 department_name                           varchar(50),
 start_date                                date,
 end_date                                  date,
 status                                    varchar(50),

 CONSTRAINT pk_dim_employee PRIMARY KEY ( employee_key ),
 CONSTRAINT fk_dim_employee_403 FOREIGN KEY ( parent_employee_key ) REFERENCES adworks.dim_employee ( employee_key ),
 CONSTRAINT fk_dim_employee_405 FOREIGN KEY ( sales_territory_key ) REFERENCES adworks.dim_sales_territory ( sales_territory_key )
)
COMMENT = 'This table holds all Employee Information';
