-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_product_subcategory
CREATE TABLE adworks.dim_product_subcategory
(
 product_subcategory_key           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 product_subcategory_alternate_key number(38,0),
 english_product_subcategory_name  varchar(50) NOT NULL,
 spanish_product_subcategory_name  varchar(50) NOT NULL,
 french_product_subcategory_name   varchar(50) NOT NULL,
 product_category_key              number(38,0),
 tester_2                          date NOT NULL,

 CONSTRAINT pk_dim_product_subcategory PRIMARY KEY ( product_subcategory_key ),
 CONSTRAINT fk_dim_product_subcategory_409 FOREIGN KEY ( product_category_key ) REFERENCES adworks.dim_product_category ( product_category_key )
);
