-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.fact_finance
CREATE TABLE adworks.fact_finance
(
 finance_key          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 date_key             number(38,0) NOT NULL,
 organization_key     number(38,0) NOT NULL,
 department_group_key number(38,0) NOT NULL,
 scenario_key         number(38,0) NOT NULL,
 account_key          number(38,0) NOT NULL,
 amount               float NOT NULL,

 CONSTRAINT fk_fact_finance_417 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key ),
 CONSTRAINT fk_fact_finance_419 FOREIGN KEY ( organization_key ) REFERENCES adworks.dim_organization ( organization_key ),
 CONSTRAINT fk_fact_finance_421 FOREIGN KEY ( department_group_key ) REFERENCES adworks.dim_department_group ( department_group_key ),
 CONSTRAINT fk_fact_finance_423 FOREIGN KEY ( scenario_key ) REFERENCES adworks.dim_scenario ( scenario_key )
)
COMMENT = 'Facts for Finance';
