-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_organization
CREATE TABLE adworks.dim_organization
(
 organization_key        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 parent_organization_key number(38,0),
 percentage_of_ownership varchar(16),
 organization_name       varchar(50),
 currency_key            number(38,0),

 CONSTRAINT pk_dim_organization PRIMARY KEY ( organization_key )
)
COMMENT = 'Dimension for Organizational Data';
