-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** adworks.dim_geography
CREATE TABLE adworks.dim_geography
(
 geography_key               number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 city                        varchar(30),
 state_province_code         varchar(3),
 state_province_name         varchar(50),
 country_region_code         varchar(3),
 english_country_region_name varchar(50),
 spanish_country_region_name varchar(50),
 french_country_region_name  varchar(50),
 postal_code                 varchar(15),
 sales_territory_key         number(38,0),
 ip_address_locator          varchar(15),

 CONSTRAINT pk_dim_geography PRIMARY KEY ( geography_key )
);
