-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_28
CREATE TABLE table_28
(
 employee_key number(38,0) NOT NULL,

 CONSTRAINT pk_1 PRIMARY KEY ( employee_key ),
 CONSTRAINT fk_42 FOREIGN KEY ( employee_key ) REFERENCES adworks.dim_employee ( employee_key )
);
