-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_23
CREATE TABLE table_23
(
 department_group_key number(38,0) NOT NULL,

 CONSTRAINT pk_1 PRIMARY KEY ( department_group_key ),
 CONSTRAINT fk_38 FOREIGN KEY ( department_group_key ) REFERENCES adworks.dim_department_group ( department_group_key )
)
COMMENT = 'hdgfh';
