-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_25
CREATE TABLE table_25
(
 customer_space_id  NOT NULL,

 CONSTRAINT pk_1 PRIMARY KEY ( customer_space_id )
)
COMMENT = 'fgdfgfd';
