-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** table_24
CREATE TABLE table_24
(
 date_key number(38,0) NOT NULL,

 CONSTRAINT pk_1 PRIMARY KEY ( date_key ),
 CONSTRAINT fk_40 FOREIGN KEY ( date_key ) REFERENCES adworks.dim_date ( date_key )
);
